### PR TITLE
fix: persist public key

### LINKED ISSUE #31: PublicKey not visible and ids:version not set
**Describe the bug**
We observed a strange behaviour, which we can't reproduce easily. We used the available last image 6.5.1
On one of the first starts the self description is not filled correctly with all values (but ids:keyValue of public key is shown correctly):

```
"ids:version": "@project.version@",
[...]
ids:keyValue": "TUlJQ[...]
```

Somehow restarting seems to help to set the correct version number. But that results in a missing ids:publicKey field.
We have no idea what goes on here. But maybe you have clues what to look for.

### PR DESCRIPTION
**Pull request by ghost**
Fixes part of Issue: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/31

Persists the connector public key in the DB.
- [x] code
- [x] test
- [x] changelog

### CODE REVIEW

File: src/main/java/io/dataspaceconnector/model/configuration/Configuration.java [hunk 1]
```diff
@@ -85,6 +86,13 @@ public class Configuration extends NamedEntity {
      */
     private String version;
 
+    /**
+     * The public key.
+     */
+    @Lob
+    @Column(columnDefinition = "TEXT")
+    private byte[] publicKey;
```
Comment (SebastianOpriel) [inline src/main/java/io/dataspaceconnector/model/configuration/Configuration.java:94]: Why is it defined as byte array?

Comment (ghost) [reply src/main/java/io/dataspaceconnector/model/configuration/Configuration.java:94]: 1. To long value for a simple string
2. most important: IAIS Java Artifact requires it to be byte[] in its builder-classes, therefore to have consistency in data management

Comment (ghost) [reply src/main/java/io/dataspaceconnector/model/configuration/Configuration.java:94]: https://github.com/International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model/blob/7d354b04f4c0dd8888dfba8ff1712d94574d080d/de/fraunhofer/iais/eis/PublicKeyImpl.java#L56

**Review by SebastianOpriel — APPROVED** [review]
