### PR TITLE
fix: route reference check

### LINKED ISSUE #355: Connector does not fetch data from backend URL
**Describe the bug**
 I create a resource in the UI and specify a service with REST-API as backend connection for remote data. But the DSC does not fetch the data from the backend properly.

**To Reproduce**
* I create a resource in the UI and specify a service with REST-API as backend connection for remote data.
* Then I use another DSC to fetch data from the created resource
* The sequence (asking provider-dsc for resource-information, getting catalog, negotiation of contract, fetching data) does not throw any error
* but the data returned is empty

**Expected behavior**
I would expect the DSC to ask the backend for data, fetch it and respond the data request from consumer-dsc with the data.

**Screenshots & Logs**
If applicable, add screenshots and logs to help explain your problem.

This is the log from the provider:
```
2022-07-18T11:24:31,224 [scheduling-1] INFO - Scanning agreements...
2022-07-18T11:24:31,224 [scheduling-1] INFO - Scanning agreements...
2022-07-18T11:25:22,230 [https-jsse-nio-8080-exec-10] DEBUG - Creating route for Dataspace Connector...
2022-07-18T11:25:22,230 [https-jsse-nio-8080-exec-10] DEBUG - Creating route for Dataspace Connector...
2022-07-18T11:25:22,237 [https-jsse-nio-8080-exec-10] DEBUG - Added route to Camel context. [routeId=(cc42c3d4-b039-4e6f-a7a0-159a49c9825a)]
2022-07-18T11:25:22,237 [https-jsse-nio-8080-exec-10] DEBUG - Added route to Camel context. [routeId=(cc42c3d4-b039-4e6f-a7a0-159a49c9825a)]
2022-07-18T11:25:31,307 [scheduling-1] INFO - Scanning agreements...
2022-07-18T11:25:31,307 [scheduling-1] INFO - Scanning agreements...
2022-07-18T11:25:52,030 [https-jsse-nio-8080-exec-2] INFO - Received incoming message.
2022-07-18T11:25:52,053 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:52,068 [https-jsse-nio-8080-exec-2] INFO - Sending response with status OK (200).
2022-07-18T11:25:56,182 [https-jsse-nio-8080-exec-10] INFO - Received incoming message.
2022-07-18T11:25:56,193 [https-jsse-nio-8080-exec-10] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:56,247 [https-jsse-nio-8080-exec-10] INFO - Sending response with status OK (200).
2022-07-18T11:25:57,007 [https-jsse-nio-8080-exec-4] INFO - Received incoming message.
2022-07-18T11:25:57,044 [https-jsse-nio-8080-exec-4] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:57,053 [https-jsse-nio-8080-exec-4] DEBUG - Contract request accepted. [agreementId=(https://myserverurl.de:8081/api/agreements/32a97545-ed39-47f1-b057-10b6ac4113c2)]
2022-07-18T11:25:57,053 [https-jsse-nio-8080-exec-4] DEBUG - Contract request accepted. [agreementId=(https://myserverurl.de:8081/api/agreements/32a97545-ed39-47f1-b057-10b6ac4113c2)]
2022-07-18T11:25:57,060 [https-jsse-nio-8080-exec-4] INFO - Sending response with status OK (200).
2022-07-18T11:25:57,311 [https-jsse-nio-8080-exec-5] INFO - Received incoming message.
2022-07-18T11:25:57,335 [https-jsse-nio-8080-exec-5] WARN - Failed to send contract agreement to clearing house. [exception=(Claims of requesting connector missing. Cannot create process at Clearing House.)]
2022-07-18T11:25:57,335 [https-jsse-nio-8080-exec-5] WARN - Failed to send contract agreement to clearing house. [exception=(Claims of requesting connector missing. Cannot create process at Clearing House.)]
2022-07-18T11:25:57,335 [https-jsse-nio-8080-exec-5] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:57,344 [https-jsse-nio-8080-exec-5] INFO - Sending response with status OK (200).
2022-07-18T11:25:57,542 [https-jsse-nio-8080-exec-7] INFO - Received incoming message.
2022-07-18T11:25:57,553 [https-jsse-nio-8080-exec-7] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:57,602 [https-jsse-nio-8080-exec-7] INFO - Sending response with status OK (200).
2022-07-18T11:25:58,071 [https-jsse-nio-8080-exec-2] INFO - Received incoming message.
2022-07-18T11:25:58,091 [https-jsse-nio-8080-exec-2] INFO - Sending request to https://provider-connector:8080/api/routes/cc42c3d4-b039-4e6f-a7a0-159a49c9825a ...
2022-07-18T11:25:58,106 [https-jsse-nio-8080-exec-2] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(401)]
2022-07-18T11:25:58,107 [https-jsse-nio-8080-exec-2] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:25:58,118 [https-jsse-nio-8080-exec-2] INFO - Sending response with status OK (200).
2022-07-18T11:26:00,125 [https-jsse-nio-8080-exec-3] INFO - Received incoming message.
2022-07-18T11:26:00,156 [https-jsse-nio-8080-exec-3] INFO - Sending request to https://provider-connector:8080/api/routes/cc42c3d4-b039-4e6f-a7a0-159a49c9825a?cb=1658143541567 ...
2022-07-18T11:26:00,163 [https-jsse-nio-8080-exec-3] WARN - Received response but response-code not in 200-299. [code=(IMSMEW0046), response-code=(401)]
2022-07-18T11:26:00,164 [https-jsse-nio-8080-exec-3] INFO - Using cached DAPS DAT. [expiration=(2022-07-18T12:06:42.000+0000)]
2022-07-18T11:26:00,176 [https-jsse-nio-8080-exec-3] INFO - Sending response with status OK (200).
2022-07-18T11:26:31,393 [scheduling-1] INFO - Scanning agreements...
```
I noticed here that there are 401 errors, which seem to be ignored.
I have tried with different configuration of my service (http/https; with and without basic Auth) none seem to have any impact.

**Desktop (please complete the following information):**
 - seen with chrome and firefox
 - I am using dataspace-connector:7.1.0 with dataspace-connector-ui:9.3.0.

**Additional context**
* I noticed, that when I edit an existing backend-connection the username and password is empty. I do not know if this intentional or could indicate some storage problem for the credentials
* when I use the exact same consumer configuration and message sequence, but instead specify a local data source in the provider and upload the data from a file everything works as expected

### PR DESCRIPTION
**Pull request by omarsilva1**
The route reference check was previously relying on the base url. Since the base url can change (e.g. when hosting locally in docker) the new check searches for the uuid in the route repository.

This very likely fixes https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/355.

### CODE REVIEW

File: src/main/java/io/dataspaceconnector/common/net/ApiReferenceHelper.java [hunk 1]
```diff
@@ -39,16 +47,20 @@ public final class ApiReferenceHelper {
...
+     * Checks whether a URL is a route reference by searching for
+     * the uuid of the url in the route repository.
      *
      * @param url The URL to check.
      * @return True, if the URL is a route reference; false otherwise.
      */
     public boolean isRouteReference(final URL url) {
-        final var routesApiUrl = getBaseUrl() + BasePath.ROUTES;
-        return url.toString().startsWith(routesApiUrl);
+        final var id = url.getPath().substring(url.getPath().lastIndexOf('/') + 1);
```
Comment (SebastianOpriel) [inline src/main/java/io/dataspaceconnector/common/net/ApiReferenceHelper.java]: I would prefer to go with a regex, which searches for the UUID at the end of the string: https://stackoverflow.com/questions/136505/searching-for-uuids-in-text-with-regex. Something like `.*\\[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$` may work

Comment (omarsilva1) [reply src/main/java/io/dataspaceconnector/common/net/ApiReferenceHelper.java]: The method now makes use of UUIDUtils where the regex is used

**Review by SebastianOpriel — APPROVED** [review]
